title: Vertretungsplan
description: Eine Android-App, welche den Vertretungsplan des FSG in Großröhrsdorf abruft und formatiert.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
